### ISSUE TITLE
[Bug] Adding video  Sources

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.eminence.2#104]
When adding Video sources the file name is blank(None) 

<img width="1581" alt="1" src="https://user-images.githubusercontent.com/2873112/139560148-607b11d3-e1bf-44e0-bdf6-91def0008687.png">

<img width="1581" alt="2" src="https://user-images.githubusercontent.com/2873112/139560153-83956907-62dc-4134-946b-5f0963374bc3.png">

Thanks

**Comment by drinfernoo** [comment]
Use "Choose item for menu" of you want it to change the action *and* label.

**Comment by Blurayx** [comment]
Ah, Thanks. 
With AH using the same method it automatically changes.

**Comment by drinfernoo** [comment]
Most (if not all) skins I use work the way it does here:

"Choose item for menu" updates both the action and label, whereas choosing "Action" or "Label" directly only modifies that thing.

**Comment by jurialmunkey** [comment]
>  With AH using the same method it automatically changes.

It shouldn't. 
Action should only change the action, not the label (and as drinfernoo points out "Choose item" will change both action and label).

Note that the first option in AH in the dialog is "Disable/Enable" which Eminence doesn't have. So all the options are shifted up in Eminence - e.g. In AH "Choose Item" is the second option, whereas in Eminence it's the first option and the second is "Action" -- so if you're going off muscle memory from AH and choosing the second option, then you'd end up selecting "Action" instead of "Choose Item" in Eminence.

**Comment by Blurayx** [comment]
Ah, sorry you're right regarding the first option😀
