### ISSUE TITLE
Widget Question

### ISSUE THREAD

**Issue by derrgoo** [jurialmunkey/skin.eminence.2#108]
Every so often when I stop an episode midway of watching, after returning to home the widget bar disappears. When I reload skin it comes back. 

No error is shown but wondering if this could be the add on or skin issue?

**Comment by jurialmunkey** [comment]
Whenever you stop watching something Kodi will reload all containers, so the widget would be reloading. It's possible that the add-on providing the widget didn't return anything at the moment (e.g. connection error etc.) but probably more likely a skin issue.

When you say that the widget bar disappears, does the background fanart disappear too? Or is the fanart still there? If the fanart is still there, what happens when you move up to the widget?

Just trying to figure out if it is a weird visibility condition in the skin, or if it's the actual widget that's not loading.

**Comment by derrgoo** [comment]
Most of the time kodi does reload the widgets upon stop which is a normal condition. 

However, the example I described is the widget bar completely leaves and  leaves only my background picture. No fanart or widget bar showing. This is when I reload skin or sometimes even have to reboot kodi. 

Thanks.

**Comment by derrgoo** [comment]
I found this was a Fen issue and he is trying to correct.
