### ISSUE TITLE
Eminence skin doesn't show the right tv show season posters . 

### ISSUE THREAD

**Issue by Valconi1** [jurialmunkey/skin.eminence.2#64]
I installed Kodi on the Shield and installed Eminence. 3.0.4. But after scanning, all the seasons of tv shows show the same poster. I can select these posters when trying to get them manually, but even then they still won't show. I did notice the other post with the same problem, and  it supposed to be fixed, but in my case the problem is still there. What can I do to solve this problem? I really like this skin.

**Comment by sleeper55** [comment]
I'm having the same issue with season posters issue 3.0.4.  I'm on Kodi 18.1 (Coreelec) using an s905x box.  As I highlight each season it shows the same tv show poster for each season, instead of the individual season poster.  Once I go into a season and highlight the episodes, it does then show the season poster artwork, so the posters are definitely there.  Love this skin.  Very well made. This is the only issue I have found.  Thanks!

**Comment by lucasdlk** [comment]
Change where made 10month ago. When the Kodi repo will be updated ?
