### ISSUE TITLE
Is there any chance of this skin being ported for v19 with Python 3 addons?

### ISSUE THREAD

**Issue by baronvertigovongrahamthesecondofsealand** [jurialmunkey/skin.eminence.2#79]
This skin is by far my favourite of all time, and now that Ive basically been forced to upgrade to Kodi v19, I feel incomplete without my beloved interface.

Do you need some help with this? I am not a Python developer (PHP is my trade), and Im a busy guy, but if it would get this skin back in prominence, I would do whatever I can.

**Comment by jurialmunkey** [comment]
Hey! Yes, I'm definitely planning on upgrading Eminence to Matrix

> Im a busy guy

It's basically this ^^^ at the moment! All my skins have been neglected due to work commitments this year but I'm definitely planning an upgrade of Eminence to Matrix when I find time.

I still have a lot of love for Eminence. I think it is my best Kodi skin in terms of a "pure" classic Kodi interface even if it isn't my daily driver (I use Arctic Horizon currently).

**Comment by jurialmunkey** [comment]
@baronvertigovongrahamthesecondofsealand - FYI beginning work here:
https://github.com/jurialmunkey/skin.eminence.2/tree/matrix-alpha

Expect a lot of things not to work but it should at least make it run on Matrix and get basic TMDbHelper ratings added.

**Comment by Khorbo** [comment]
Thanks for your work and time spending on this skin. I use Eminence 2 for years and my family love it. I was planning to upgrade kodi to matrix, but without Eminence 2 our whole media experience will be broken :) i don't think my wife would talk to me anymore if kodi dont have my tweaked Eminence 2 interface... You just save a happy family ;)

Sorry for my english, french is my main language.

**Comment by baronvertigovongrahamthesecondofsealand** [comment]
Absolutely brilliant, thank you so much!

**Comment by jurialmunkey** [comment]
FYI - Matrix development moved to master branch.

Zipped pre-release versions will be available under releases until ready for official repo:
https://github.com/jurialmunkey/skin.eminence.2/releases
