### ISSUE TITLE
Pressing left of first tile of home bar registers as enter on widget item

### ISSUE THREAD

**Issue by meesterexx** [jurialmunkey/skin.eminence.2#82]
This is skin specific and not addon specific as I have tried with both TMDBHelper and a 3rd party addon. You can see from the screenshots attached, if I am on the 1st home bar tile (Shows) and press left arrow once to go to the last tile (Power), it acts as if I have pressed enter on a focused widget item. In the case of TMDBHelper, it gets the item details and pops up the player dialog, for the 3rd party addon it begins the addon scrape for the item.

Please note, to get the color picker and a favorites widget working, I had to install skin helper service, colorpicker and widgets. I installed Marcelveldt's repo from your repo. I don't know if this has any impact on the issue:
 
![skinhelper](https://user-images.githubusercontent.com/13154733/134707143-f7c86eb6-ab82-454a-a6a2-5a8f512f792d.PNG)

![screenshot00001](https://user-images.githubusercontent.com/13154733/134706414-2cfab62a-0d91-4d09-9cdf-edff9abbd3fb.png)

![screenshot00002](https://user-images.githubusercontent.com/13154733/134706430-a265b2e4-45e2-4999-8959-94631159cd3f.png)

**Comment by jurialmunkey** [comment]
I can't reproduce. It sounds like a skin shortcuts setup issue. Can you give me your skinshortcuts-includes.xml file from the 16x9 folder in the skin? 

BTW - skinhelper is fine to install, it just isn't _necessary_ anymore to make the skin work. There's still a few places where it's features are used like the colorpicker - but I'll be implementing replacements for these.

**Comment by jurialmunkey** [comment]
Well that was painful to try to find the source of the issue but I think I finally figured it out. The weather widget is really a list of weather fanarts which the background image loads the current one using `$INFO[ListItem.FileNameAndPath]`. The problem is there's a slight delay between the widget loading and the infolabel updating, so the image control is trying to open the FileNameAndPath of the previous widget thereby causing the previous plugin play path to launch.

I found that switching ListItem.FileNameAndPath to ListItem.PicturePath instead appears to solve it since PicturePath is only filled when FileNameAndPath is an image (so PicturePath will be blank for a "normal" widget).

Anyway, can you test 4.0.4 and see if it fixes for you?

**Comment by meesterexx** [comment]
That fixed it for me. Excellent sleuthing, thank you!

I would like to also point out one other thing with the weather widget, and that hitting enter on the focused weather widget to launch weather takes you to a full screen blank weather fanart with no weather information or gui elements, only the fanart. Launching weather from a submenu item however works fine.

This is not really an issue for me as it's not something I normally do, I use weather just for the widget display, but I wanted to point it was not functioning as expected.

Thanks again for the fix on the menu navigation, much appreciated.
